version: '3'

env:
  WORD: world

tasks:

  helloworld:

    cmds:
      - echo "hello, $WORD!"
    env:
      GREETING: hello

  byeworld:
    cmds:
      - echo "$GREETING, $WORD!"
    env:
      GREETING: bye

  buildpython:
    cmds:
      - python hello.py

  all:
    deps: [buildpython]